<script setup lang="ts">
import SanitizedHtml from "@/components/SanitizedHtml";
import { useRedTeamReport } from "@/composables/useRedTeamReport";

const { html, error, isLoading } = useRedTeamReport();
</script>

<template>
  <section class="redteam">
    <header class="redteam__head">
      <h1 class="redteam__title">
        Red Team
      </h1>
      <p class="muted">
        The latest adversarial report — injection corpora run against the firewall, generated by
        <code>make red-team</code>.
      </p>
    </header>

    <p
      v-if="isLoading"
      class="card muted"
    >
      Loading report…
    </p>
    <div
      v-else-if="error"
      class="banner banner--err"
    >
      {{ error }}
    </div>
    <SanitizedHtml
      v-else
      tag="article"
      class="redteam__report card"
      :html="html"
    />
  </section>
</template>

<style scoped lang="scss">
@use "@/styles/tokens" as *;

.redteam {
  display: flex;
  flex-direction: column;
  gap: $gap;

  &__title {
    margin: 0 0 0.25rem;
  }

  &__report {
    :deep(h1),
    :deep(h2),
    :deep(h3) {
      margin: 1.2rem 0 0.6rem;
    }

    :deep(table) {
      width: 100%;
    }

    :deep(code) {
      font-family: $mono;
    }

    :deep(pre) {
      background: $bg;
      border: 1px solid $border;
      border-radius: $radius;
      padding: 0.75rem;
      overflow-x: auto;
    }
  }
}
</style>
