"""Generate committed JSON Schema snapshots for the public contracts.

Run via ``make schemas``. The output is deterministic and idempotent: the
schema files are sorted-key, newline-terminated, and regenerated byte-for-byte
on every run. A committed snapshot + the snapshot test (``test_schema_snapshot``)
turns any change to a public model into a deliberate, reviewed act — the
mechanism behind ADR-004's semver stability for ``EvidenceRecord``.

Bump rule: changing ``EvidenceRecord.schema_version`` (and therefore its schema)
requires an ADR. The v0 schema previewed here is formalized as ADR-006 in
phase 5.
"""

from __future__ import annotations

import json
from pathlib import Path

from contextguard_contracts import (
    Chunk,
    EvidenceRecord,
    GuardedContext,
    QueryRequest,
    QueryResponse,
    UserContext,
)
from contextguard_policy_dsl import Policy
from pydantic import BaseModel

# Types whose JSON Schema we publish. Consumed later by the Monaco policy editor
# and the OpenAPI -> TS generation (Milestone B).
EXPORTED: dict[str, type[BaseModel]] = {
    "evidence": EvidenceRecord,
    "chunk": Chunk,
    "guarded_context": GuardedContext,
    "user_context": UserContext,
    "query_request": QueryRequest,
    "query_response": QueryResponse,
    "policy": Policy,
}

SCHEMA_DIR = Path(__file__).resolve().parent.parent / "packages" / "contracts" / "schemas"


def render_schema(model: type[BaseModel]) -> str:
    """Render a model's JSON Schema as deterministic, newline-terminated text."""
    schema = model.model_json_schema()
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def write_schemas(target_dir: Path = SCHEMA_DIR) -> list[Path]:
    """Write every exported schema; return the paths written."""
    target_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, model in EXPORTED.items():
        path = target_dir / f"{name}.schema.json"
        path.write_text(render_schema(model), encoding="utf-8")
        written.append(path)
    return written


def main() -> None:
    for path in write_schemas():
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
