/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/guard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Guard Scan
         * @description Adjudicate caller-supplied chunks against the policy - no model call.
         */
        post: operations["guard_scan_v1_guard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query
         * @description Retrieve, guard, build a cited prompt, and return a grounded answer.
         */
        post: operations["query_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Chunk
         * @description A retrieved unit of context. Enrichment fields stay empty until phase 3.
         */
        Chunk: {
            classification: components["schemas"]["Classification"];
            /** Doc Id */
            doc_id: string;
            /** Id */
            id: string;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: string;
            };
            /**
             * Pii Spans
             * @default []
             */
            pii_spans: components["schemas"]["Span"][];
            /**
             * Risk Signals
             * @default []
             */
            risk_signals: components["schemas"]["RiskSignal"][];
            /**
             * Secret Spans
             * @default []
             */
            secret_spans: components["schemas"]["Span"][];
            /** Tenant */
            tenant: string;
            /** Text */
            text: string;
        };
        /**
         * ChunkDecision
         * @description The guard's verdict for one chunk, with auditable reasons.
         */
        ChunkDecision: {
            /** Chunk Id */
            chunk_id: string;
            outcome: components["schemas"]["Outcome"];
            /**
             * Policies Triggered
             * @default []
             */
            policies_triggered: string[];
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
        };
        /**
         * Classification
         * @description Sensitivity label attached to a chunk/document, lowest to highest.
         * @enum {string}
         */
        Classification: "public" | "internal" | "confidential" | "restricted";
        /**
         * GuardRequest
         * @description A scan-only request: the query plus the candidate chunks to adjudicate.
         *
         *     Identity is NOT carried here - it is derived from the verified Bearer token
         *     at the HTTP boundary (ADR-015). The caller supplies the chunks to guard, so
         *     the scan runs without retrieval or a model call (Milestone B3.3).
         */
        GuardRequest: {
            /**
             * Candidate Chunks
             * @default []
             */
            candidate_chunks: components["schemas"]["Chunk"][];
            /** Query */
            query: string;
        };
        /**
         * GuardedContext
         * @description The result of ``guard()``: what survived, every decision, token deltas.
         */
        GuardedContext: {
            /**
             * Allowed Chunks
             * @default []
             */
            allowed_chunks: components["schemas"]["Chunk"][];
            /**
             * Decisions
             * @default []
             */
            decisions: components["schemas"]["ChunkDecision"][];
            /**
             * Tokens After
             * @default 0
             */
            tokens_after: number;
            /**
             * Tokens Before
             * @default 0
             */
            tokens_before: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Outcome
         * @description What the guard decided to do with a single chunk.
         * @enum {string}
         */
        Outcome: "allowed" | "blocked" | "redacted";
        /**
         * QueryRequest
         * @description A RAG query: what is asked and how many chunks to retrieve.
         *
         *     Identity is NOT carried here - it is derived from the verified Bearer token
         *     at the HTTP boundary (ADR-015), never asserted by the client body.
         */
        QueryRequest: {
            /**
             * K
             * @default 5
             */
            k: number;
            /** Query */
            query: string;
        };
        /**
         * QueryResponse
         * @description The grounded answer plus the retrieval hits and the guard's verdict.
         */
        QueryResponse: {
            /** Answer */
            answer: string;
            guarded_context: components["schemas"]["GuardedContext"];
            /**
             * Retrieved Chunks
             * @default []
             */
            retrieved_chunks: components["schemas"]["RetrievedChunk"][];
        };
        /**
         * RetrievedChunk
         * @description One retrieval hit returned to the caller: identity, text, fused score.
         */
        RetrievedChunk: {
            classification: components["schemas"]["Classification"];
            /** Doc Id */
            doc_id: string;
            /** Id */
            id: string;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: string;
            };
            /** Score */
            score: number;
            /** Tenant */
            tenant: string;
            /** Text */
            text: string;
        };
        /**
         * RiskSignal
         * @description An adversarial signal detected in a chunk, with a confidence weight.
         */
        RiskSignal: {
            /** Evidence */
            evidence: string;
            type: components["schemas"]["RiskType"];
            /** Weight */
            weight: number;
        };
        /**
         * RiskType
         * @description Adversarial signal categories a chunk may carry (filled from phase 3).
         * @enum {string}
         */
        RiskType: "injection" | "role_override" | "exfiltration" | "hidden_text" | "tool_instruction";
        /**
         * Span
         * @description A half-open ``[start, end)`` character range of sensitive text.
         */
        Span: {
            /** End */
            end: number;
            /** Start */
            start: number;
            /** Subtype */
            subtype: string;
            type: components["schemas"]["SpanType"];
        };
        /**
         * SpanType
         * @description Kind of sensitive span detected within a chunk's text.
         * @enum {string}
         */
        SpanType: "pii" | "secret";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    guard_scan_v1_guard_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardedContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_v1_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
